/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboard;

import java.sql.Connection;

/**
 *
 * @author HP
 */

    import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import koneksi.konek;

public class tampilan_login extends javax.swing.JFrame {

    /**
     * Creates new form tampilan_login
     */
    public tampilan_login() {
        initComponents();
    }
    
     void tampil(){
        try {
            String sql = "select * from user where email = '"+txt_email.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.konek.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rst = pst.executeQuery();
            if(rst.next()){
                tampilan_dashboard.txt_iduser.setText(rst.getString("id_user"));
                tampilan_dashboard.id_detail.setText(rst.getString("id_detail"));
            }
        } catch (Exception e) {
        }
    }
     void tampildetail(){
        try {
            String sql = "SELECT user.id_user, detail_user.id_detail from user join detail_user on user.id_user = detail_user.id_user where user.email = '"+txt_email.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.konek.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rst = pst.executeQuery();
            if(rst.next()){
                tampilan_dashboard.id_detail.setText(rst.getString("id_detail"));
            }
        } catch (Exception e) {
        }
    }
     
     void tampildokter(){
        try {
            String sql = "select user.id_user, dokter.nama_dokter,dokter.id_dokter from user join dokter on user.id_user = dokter.id_user where password = '"+txt_pass.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.konek.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rst = pst.executeQuery();
            if(rst.next()){
                dokter.tampilan_list_konsul.id_dokter.setText(rst.getString("id_dokter"));
            }
        } catch (Exception e) {
        }
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txt_email = new javax.swing.JTextField();
        txt_pass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(790, 810, 340, 70);

        txt_email.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        txt_email.setForeground(new java.awt.Color(75, 116, 55));
        txt_email.setBorder(null);
        txt_email.setOpaque(false);
        getContentPane().add(txt_email);
        txt_email.setBounds(770, 460, 510, 50);

        txt_pass.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(75, 116, 55));
        txt_pass.setBorder(null);
        txt_pass.setOpaque(false);
        getContentPane().add(txt_pass);
        txt_pass.setBounds(770, 570, 510, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Halaman Login.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String email = txt_email.getText();
        String password = txt_pass.getText();
        
        try {
                    String sql = "SELECT * from user where email='" + email + "' AND password='" + password + "'";
                    java.sql.Connection conn = (Connection) koneksi.konek.configDB();
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    java.sql.ResultSet rst = pst.executeQuery();

                    while (rst.next()) {
                        int level = rst.getInt("level");
                        
                        if (level == 2) {
                            JOptionPane.showMessageDialog(this, "Login Berhasil");
                            new dokter.tampilan_list_konsul().setVisible(true);
                            this.setVisible(false);
                        tampildokter();
                        }else{
                            JOptionPane.showMessageDialog(this, "Login Berhasil");
                        new tampilan_dashboard().setVisible(true);
                        this.setVisible(false);
                        tampil();
                            tampildetail();
                        }
                        
                        
                    }
                } catch (Exception e) {
                    System.out.println("gagal Login"+ e.getMessage());
                }

//        new tampilan_dashboard().setVisible(true);
//        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tampilan_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tampilan_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tampilan_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tampilan_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tampilan_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_pass;
    // End of variables declaration//GEN-END:variables
}
