/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboard;

import static dashboard.tampilan_biodata.id_detail;
import static dashboard.tampilan_biodata.txt_iduser;
import static dashboard.tampilan_dashboard.id_detail;
import static dashboard.tampilan_dashboard.tampil_hasil_konsul;
import dokter.tampilan_input_hasil;
import static dokter.tampilan_konsul_pelanggan.id_user;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class tampilan_konsultasi extends javax.swing.JFrame {

    /**
     * Creates new form tampilan_konsultasi
     */
    public tampilan_konsultasi() {
        initComponents();
        tampil_konsul();
    }
    public static void tampil_konsul(){
        try {
            String sql = "select konsultasi.id_konsultasi,konsultasi.imt_bti,konsultasi.advice,konsultasi.id_detail,konsultasi.id_dokter,konsultasi.total, detail_user.nik from konsultasi join detail_user on konsultasi.id_detail = detail_user.id_detail where konsultasi.id_detail = '"+id_detail.getText()+"' order by id_detail desc";
            java.sql.Connection conn = (Connection)koneksi.konek.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rst = pst.executeQuery();
            if(rst.next()){
                tampilan_konsultasi.txt_imt.setText(rst.getString("imt_bti"));
                tampilan_konsultasi.txt_total.setText(rst.getString("total"));
                tampilan_konsultasi.txt_advice.setText(rst.getString("advice"));
                tampilan_konsultasi.nik.setText(rst.getString("nik"));
            }
        } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);

        }
    }
     public static void tampil_hasil_konsul(){
        try {
            String sql = "select hasil_konsultasi.id_rm,hasil_konsultasi.hasil,hasil_konsultasi.id_detail,hasil_konsultasi.id_dokter, dokter.nama_dokter,dokter.jam_operasi_mulai,dokter.jam_operasi_selesai from hasil_konsultasi join dokter on hasil_konsultasi.id_dokter = dokter.id_dokter where id_detail = '"+id_detail.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.konek.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rst = pst.executeQuery();
            if(rst.next()){
                tampilan_report.no_rm.setText(rst.getString("id_rm"));
                tampilan_report.hasil.setText(rst.getString("hasil"));
                tampilan_report.nama_dokter.setText(rst.getString("nama_dokter"));
                tampilan_report.jam_mulai.setText(rst.getString("jam_operasi_mulai"));
                tampilan_report.jam_selesai.setText(rst.getString("jam_operasi_selesai"));
            }
        } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);

        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_total = new javax.swing.JLabel();
        nik = new javax.swing.JLabel();
        txt_imt = new javax.swing.JTextField();
        txt_advice = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        txt_iduser = new javax.swing.JLabel();
        id_detail = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        getContentPane().setLayout(null);

        txt_total.setText("jLabel3");
        getContentPane().add(txt_total);
        txt_total.setBounds(1360, 810, 180, 30);
        getContentPane().add(nik);
        nik.setBounds(900, 310, 330, 30);
        getContentPane().add(txt_imt);
        txt_imt.setBounds(690, 490, 500, 160);
        getContentPane().add(txt_advice);
        txt_advice.setBounds(690, 780, 500, 150);

        jButton10.setContentAreaFilled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(0, 220, 480, 110);

        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(0, 340, 480, 110);

        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(0, 469, 480, 100);

        jButton6.setContentAreaFilled(false);
        jButton6.setInheritsPopupMenu(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(0, 579, 480, 110);

        jButton7.setContentAreaFilled(false);
        jButton7.setInheritsPopupMenu(true);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(0, 710, 480, 140);
        getContentPane().add(txt_iduser);
        txt_iduser.setBounds(1020, 70, 170, 40);

        id_detail.setText("jLabel2");
        getContentPane().add(id_detail);
        id_detail.setBounds(910, 60, 51, 20);

        jButton8.setContentAreaFilled(false);
        jButton8.setInheritsPopupMenu(true);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(0, 850, 480, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Hasil Konsul.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       new tampilan_dashboard().setVisible(true);
       String id_details = id_detail.getText();
        tampilan_dashboard.id_detail.setText(id_details);
         String id = txt_iduser.getText();
        tampilan_dashboard.txt_iduser.setText(id);
        dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        new tampilan_biodata().setVisible(true);
        String id_details = id_detail.getText();
        tampilan_biodata.id_detail.setText(id_details);
         String id = txt_iduser.getText();
        tampilan_biodata.txt_iduser.setText(id);
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new tampilan_choose_doctor().setVisible(true);
        String id_details = id_detail.getText();
        tampilan_choose_doctor.id_detail.setText(id_details);
         String id = txt_iduser.getText();
        tampilan_choose_doctor.txt_iduser.setText(id);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new tampilan_konsul_user().setVisible(true);
        String id_details = id_detail.getText();
        tampilan_konsul_user.id_detail.setText(id_details);
         String id = txt_iduser.getText();
        tampilan_konsul_user.txt_id_user.setText(id);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new tampilan_report().setVisible(true);
        String id_details = id_detail.getText();
        tampilan_konsultasi.id_detail.setText(id_details);
         String id = txt_iduser.getText();
        tampilan_konsultasi.txt_iduser.setText(id);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        new tampilan_report().setVisible(true);
               tampil_hasil_konsul();

        String id = txt_iduser.getText();
        String id_details = id_detail.getText();
        tampilan_report.txt_iduser.setText(id);
        tampilan_report.id_detail.setText(id_details);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tampilan_konsultasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tampilan_konsultasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tampilan_konsultasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tampilan_konsultasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tampilan_konsultasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel id_detail;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel nik;
    public static javax.swing.JTextField txt_advice;
    public static javax.swing.JLabel txt_iduser;
    public static javax.swing.JTextField txt_imt;
    public static javax.swing.JLabel txt_total;
    // End of variables declaration//GEN-END:variables
}
