/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dokter;

import dashboard.tampilan_create_akun;
import static dokter.tampilan_konsul_pelanggan.id_konsul;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class tampilan_list_konsul extends javax.swing.JFrame {

    /**
     * Creates new form tampilan_list_konsul
     */
    public tampilan_list_konsul() {
        initComponents();
        konsultasi();
    }
    void tampil(){
        try {
            String sql = "select * from konsultasi_user where id_konsultasi_user = '"+id_konsul.getText()+"';";
            java.sql.Connection conn = (Connection)koneksi.konek.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rst = pst.executeQuery();
            if(rst.next()){
                tampilan_konsul_pelanggan.konsul_pelanggan.setText(rst.getString("isi_konsultasi"));
            }
        } catch (Exception e) {
        }
    }
    void tampiluser(){
        try {
            String sql = " select konsultasi_user.id_user from konsultasi_user where id_konsultasi_user = '"+id_konsul.getText()+"';";
            java.sql.Connection conn = (Connection)koneksi.konek.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rst = pst.executeQuery();
            if(rst.next()){
                tampilan_konsul_pelanggan.id_user.setText(rst.getString("id_user"));
            }
        } catch (Exception e) {
        }
    }
    
      private void konsultasi(){
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Id konsultasi");
        tbl.addColumn("Nama Lengkap");
        tbl.addColumn("Isi Konsultasi");
        tbl.addColumn("Nama Dokter");
        
        
       
        try {
            Statement s = koneksi.konek.configDB().createStatement();
            ResultSet rs = s.executeQuery(" select konsultasi_user.id_konsultasi_user,detail_user.nama_lengkap, konsultasi_user.isi_konsultasi, dokter.nama_dokter,dokter.id_dokter from detail_user join konsultasi_user on detail_user.id_user = konsultasi_user.id_user join dokter on konsultasi_user.id_dokter = dokter.id_dokter;");
            
            
            while(rs.next())
            {
                tbl.addRow(new Object[] {
                    rs.getString("id_konsultasi_user"),
                    rs.getString("nama_lengkap"),
                    rs.getString("isi_konsultasi"),
                    rs.getString("nama_dokter"),
             
                });
                tb_list.setModel(tbl);
                
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal"+e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id_user = new javax.swing.JLabel();
        id_konsul = new javax.swing.JLabel();
        id_dokter = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_list = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        id_user.setText("jLabel2");
        getContentPane().add(id_user);
        id_user.setBounds(660, 80, 51, 20);

        id_konsul.setText("jLabel2");
        getContentPane().add(id_konsul);
        id_konsul.setBounds(910, 70, 51, 20);

        id_dokter.setText("jLabel2");
        getContentPane().add(id_dokter);
        id_dokter.setBounds(750, 120, 51, 20);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1290, 930, 310, 80);

        tb_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_listMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tb_listMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tb_list);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(740, 360, 880, 510);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/List Konsul Pelanggan.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_listMouseClicked
        int row = tb_list.getSelectedRow();
        id_konsul.setText(tb_list.getValueAt(row, 0).toString());
//        pemeriksaan.po.id_daftar.setText(tabel1.getValueAt(row, 0).toString());
    }//GEN-LAST:event_tb_listMouseClicked

    private void tb_listMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_listMousePressed
        int row = tb_list.getSelectedRow();
        id_konsul.setText(tb_list.getValueAt(row, 0).toString());
    }//GEN-LAST:event_tb_listMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         new tampilan_konsul_pelanggan().setVisible(true);
         tampilan_konsul_pelanggan.id_konsul.setText(id_konsul.getText());
         tampil();
         tampiluser();
        dispose();
        


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tampilan_list_konsul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tampilan_list_konsul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tampilan_list_konsul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tampilan_list_konsul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tampilan_list_konsul().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel id_dokter;
    private javax.swing.JLabel id_konsul;
    private javax.swing.JLabel id_user;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_list;
    // End of variables declaration//GEN-END:variables
}
